This is my test notebook which help me figure out some coding related issues before updating the .py files.

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('./data/sample.csv')
df.head(25)

   created_date        borough channel    complaint_type  response_time_days
0    2024-02-02         Queens     Web          Plumbing               18.27
1    2024-10-09      Manhattan   Phone          Plumbing                3.52
2    2024-08-26         Queens   Phone           Rodents                2.34
3    2024-06-09       Brooklyn     Web           Rodents                2.08
4    2024-06-07          Bronx     App          Plumbing                5.95
5    2024-11-09       Brooklyn     Web  Street Condition                9.78
6    2024-02-01       Brooklyn     Web   Illegal Parking               27.82
7    2024-09-11         Queens   Phone  Street Condition                3.56
8    2024-03-14       Brooklyn   Phone   Illegal Parking                5.72
9    2024-02-04      Manhattan   Phone          Plumbing                9.96
10   2024-07-11       Brooklyn     Web  Street Condition                6.76
11   2024-12-22       Brooklyn     App   Illegal Parking                6.34
12   2024-09-25       Brooklyn     App             Noise               14.16
13   2024-10-04       Brooklyn     App          Plumbing                5.82
14   2024-09-18       Brooklyn     App  Street Condition                2.25
15   2024-10-13       Brooklyn     App  Street Condition               12.27
16   2024-07-06       Brooklyn   Phone   Illegal Parking                1.10
17   2024-02-16         Queens   Phone    Heat/Hot Water                9.22
18   2024-11-02       Brooklyn     Web   Illegal Parking                5.38
19   2024-06-13  Staten Island     Web          Plumbing                3.92
20   2024-07-01          Bronx   Phone  Street Condition                5.12
21   2024-05-15       Brooklyn     Web             Noise                4.82
22   2024-03-07       Brooklyn     Web  Street Condition                3.76
23   2024-12-04         Queens     Web    Heat/Hot Water                6.34
24   2024-10-12          Bronx   Phone  Street Condition                4.77

In [3]:
df['complaint_type'].value_counts().index.tolist()[0]

'Heat/Hot Water'

In [4]:
df['response_time_days'].median()

np.float64(5.005000000000001)

In [5]:
len(df)

600

In [6]:
df.groupby("borough", as_index=False)["response_time_days"].median().rename(columns={"response_time_days": "median_response_days"}).sort_values("median_response_days", ascending=False)

         borough  median_response_days
0          Bronx                 6.770
1       Brooklyn                 6.370
3         Queens                 4.770
4  Staten Island                 4.735
2      Manhattan                 3.420

In [7]:
df_2 = df['borough'].value_counts().reset_index()
#data.columns
df_2.head()
fig = px.bar(df_2, x='borough', y='count')
fig.show()